name: Test Hello Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello Action
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECTION_NAME: "hello"
